services:
  fastchat-controller:
    image: renning22/dedev-inference:latest
    ports:
      - "21001:21001"
    entrypoint: ["python3", "-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "21001"]
  fastchat-model-worker-0:
    volumes:
      - /data/huggingface:/data/huggingface
    image: renning22/dedev-inference:latest
    shm_size: '10gb' 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1', '2', '3']
              capabilities: [gpu]
    entrypoint: ["python3", "-m", "fastchat.serve.vllm_worker", "--enforce-eager", "--max-model-len=102400", "--num-gpus=4", "--model-path", "microsoft/Phi-3-mini-128k-instruct", "--worker-address", "http://fastchat-model-worker-0:21002", "--controller-address", "http://fastchat-controller:21001", "--host", "0.0.0.0", "--port", "21002"]
  fastchat-api-server:
    image: renning22/dedev-inference:latest
    ports:
      - "8000:8000"
    entrypoint: ["python3", "-m", "fastchat.serve.openai_api_server", "--api-keys=trapile.ai", "--controller-address", "http://fastchat-controller:21001", "--host", "0.0.0.0", "--port", "8000"]
