torchrun --nproc_per_node=6 --master_port=20001 ../fastchat/train/train_mem.py \
    --model_name_or_path google/gemma-7b-it \
    --data_path data/nectar_20k.json \
    --output_dir /data/ning/gemma_7b_nectar_20k_1 \
    --resume_from_checkpoint True \
    --num_train_epochs 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 2e-5 \
    --weight_decay 0.1 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap offload" \
    --fsdp_transformer_layer_cls_to_wrap 'GemmaDecoderLayer' \
    --bf16 True \
    --tf32 False \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --lazy_preprocess False